// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApplication.Services.Database;
using ApplicationContext = WinFormsApplication.Services.Database.ApplicationContext;

#nullable disable

namespace WinFormsApplication.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221112154955_createSettlementTable")]
    partial class createSettlementTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");
#pragma warning restore 612, 618
        }
    }
}
